### PR TITLE
Add amd-pstate-epp governor support.

### PR DESCRIPTION
**Pull request by ghost**
The new 'amd-pstate-epp' landed in kernel 6.3, and acts slightly differently from 'amd-pstate'.

Adding the 'amd-pstate-epp' strings to the slimbookcontrollerpreferences.py script enables the configuration tabs to work once again. The driver works identically to the intel_pstate one, so use that one's governor configs instead.

Fix based on findings from issue #104

### CODE REVIEW

**Comment by siddhpant** [comment]
Please squash the commits.

**Comment by siddhpant** [comment]
I still cannot see the tabs:

image

**Comment by slimbook** [comment]
It might be the underscore, can you update the code to test it manually?

**Comment by ghost** [comment]
Weird, for me the driver is named "amd-pstate-epp". But it's entirely possible both names are valid.

**Comment by siddhpant** [comment]
> Weird, for me the driver is named "amd-pstate-epp". But it's entirely possible both names are valid.

Oh alright, there has been a rename. Hyphenated is the new name. Seems like Debian testing didn't include those patches yet in 6.3. It was backported to 6.3 a week ago. The new stable, 6.3.11, released on 1st July with the patch.

https://lore.kernel.org/lkml/2023070145-pureness-conjure-c024@gregkh/

Edit: By "hyphenated" I meant `amd-pstate-epp`. In my case, the name has underscores (`amd_pstate_epp`).

**Comment by siddhpant** [comment]
Adding `amd_pstate_epp` to various places as in this PR makes sbat working again. Thanks.

Though, there is no need to add that, since the name with dashes has been backported to 6.3 stable kernel. EPP driver was introduced in 6.3.

**Pull request merged**
