### PR TITLE
Update battery information

### PR DESCRIPTION
**Pull request by ehooo**
I see that this functionality is on the TODO list

### CODE REVIEW

**Comment by slimbook** [comment]
Great, it was a cool enhancement! Could you make the pull request to the development branch? I think it's better to keep the main branch with the current uploaded version source-code, and keep development in a different branch.

**Comment by ehooo** [comment]
There is confict, and i'm out this weekend, i'll do on monday

**Comment by MarSlimbook** [comment]
Okey no hurry, thanks!!

**Comment by ehooo** [comment]
@MarSlimbook I just update the PR.
Thanks

**Comment by slimbook** [comment]
Great! Thank you!

**Pull request merged**
