### PR TITLE
Deploy script

### LINKED ISSUE #29: Include deployment script
To avoid package-manager dependency, it could be a good idea to have an installation/deployment script to deploy repository in to the system.

This method could avoig tasks to generate all distros packages, reducing releases complexity and adding compatibility for non-debian distros (I use Manjaro BTW)

More over, developers will have an easy way to "test in production" before make any pullrequest (I want to collaborate Slimbook as developer BTW)

Regards! :smile:

### PR DESCRIPTION
**Pull request by Carlosmape**
The idea is to have a script to deploy repository in the system (in any distro)

### CODE REVIEW

**Comment by ehooo** [comment]
Hello @Carlosmape 
I think is better idea use the debian/install file as template to generate the content.

**Comment by Carlosmape** [comment]
> Hello @Carlosmape I think is better idea use the debian/install file as template to generate the content.

I thought to read `debian/install` and do `sudo cp` line by line to avoid this script maintenance, but then the script will be depend on that file, I will do it by the momment. Thanks!

UPDATE: the trouble is that I should create directory structure before do the copies

**Comment by Carlosmape** [comment]
@slimbook I modified replace.sh script (in this commit d9aeec2e3eb2e74e4c419b2fe1d5445002d453af) but i am not sure if it will work properly

**Comment by slimbook** [comment]
Okey, I've seen it, I'll test it (I'll see what to do with those files, maybe could be merged)

**Review by slimbook — COMMENTED** [review]
Looks good!

**Comment by Carlosmape** [comment]
Should I add something? or may I merge this PR? @slimbook

**Comment by slimbook** [comment]
I was going to ask the same :D, I'll merge it

**Pull request merged**
